Config = {}
Config.CancelAnimationCommand = 'c'
Config.CancelAnimationDefultKey = 'X'
Config.DisableInCar = false
Config.ChangeAnimationSetCommand = 'emoteset'
Config.SaveWalkStyle = true
Config.SaveFaceExpressionStyle = true 
Config.QuickAnims = true 
Config.QuickAnimKey1 = '1'
Config.QuickAnimKey2 = '2'
Config.QuickAnimKey3 = '3'
Config.QuickAnimKey4 = '4'
Config.QuickAnimKey5 = '5'

Config.Animations = {
    ["seat"] = {title = "S'asseoir", category = "main", animDict = "rcmtmom_1leadinout", animName = "tmom_1_rcm_p3_leadout_loop", animFlag = 15},
    ["seat2"] = {title = "S'asseoir 2", category = "main", animDict = "rcmnigel1a_band_groupies", animName = "idle_a_m1", animFlag = 15},
    ["seat3"] = {title = "S'asseoir 3", category = "main", animDict = "anim@heists@fleeca_bank@hostages@intro", animName = "intro_loop_ped_a", animFlag = 15},
    ["seat4"] = {title = "S'asseoir 4", category = "main", animDict = "rcm_barry3", animName = "barry_3_sit_loop", animFlag = 15},
    ["seat5"] = {title = "S'asseoir 5", category = "main", animDict = "anim@amb@business@bgen@bgen_no_work@", animName = "sit_phone_phoneputdown_wakeup_nowork", animFlag = 15},
    ["seat6"] = {title = "S'asseoir 6", category = "main", animDict = "timetable@ron@ig_5_p3", animName = "ig_5_p3_base", animFlag = 15},
    ["seat7"] = {title = "S'asseoir 7", category = "main", animDict = "timetable@reunited@ig_10", animName = "base_amanda", animFlag = 15},
    ["seat8"] = {title = "S'asseoir 8", category = "main", animDict = "timetable@ron@ig_3_couch", animName = "base", animFlag = 15},
    ["seat9"] = {title = "S'asseoir 9", category = "main", animDict = "timetable@jimmy@mics3_ig_15@", animName = "mics3_15_base_tracy", animFlag = 15},
    ["seat10"] = {title = "S'asseoir 10", category = "main", animDict = "timetable@jimmy@mics3_ig_15@", animName = "idle_a_jimmy", animFlag = 15},
    ["seat11"] = {title = "S'asseoir 11", category = "main", animDict = "anim@amb@nightclub@lazlow@lo_alone@", animName = "lowalone_base_laz", animFlag = 15},
    ["seat12"] = {title = "S'asseoir 12", category = "main", animDict = "timetable@jimmy@mics3_ig_15@", animName = "mics3_15_base_jimmy", animFlag = 15},
    ["seat13"] = {title = "S'asseoir 13", category = "main", animDict = "mp_safehouse", animName = "lap_dance_player", animFlag = 15},
    ["seat14"] = {title = "S'asseoir 14", category = "main", animDict = "switch@trevor@floyd_crying", animName = "console_loop_floyd", animFlag = 15},
    ["seat17"] = {title = "S'asseoir 15", category = "main", animDict = "timetable@michael@on_sofaidle_a", animName = "sit_sofa_a", animFlag = 15},
    ["seat18"] = {title = "S'asseoir 16", category = "main", animDict = "timetable@michael@on_sofaidle_b", animName = "sit_sofa_d", animFlag = 15},
    ["seat19"] = {title = "S'asseoir 17", category = "main", animDict = "timetable@michael@on_sofaidle_c", animName = "sit_sofa_g", animFlag = 15},
    ["seat20"] = {title = "S'asseoir 18", category = "main", animDict = "safe@michael@ig_3", animName = "cigar_idle_a_michael", animFlag = 15},
    ["seat21"] = {title = "S'asseoir 19", category = "main", animDict = "switch@franklin@stripclub", animName = "002113_02_fras_15_stripclub_idle", animFlag = 15},
    ["seat22"] = {title = "S'asseoir 20", category = "main", animDict = "switch@michael@parkbench_smoke_ranger", animName = "parkbench_smoke_ranger_loop", animFlag = 15},
    ["seat23"] = {title = "S'asseoir 21", category = "main", animDict = "switch@michael@smoking2", animName = "loop", animFlag = 15},
    ["seat24"] = {title = "S'asseoir 22", category = "main", animDict = "switch@michael@tv_w_kids", animName = "001520_02_mics3_14_tv_w_kids_idle_mic", animFlag = 15},
    ["seat25"] = {title = "S'asseoir 23", category = "main", animDict = "timetable@denice@ig_4", animName = "base", animFlag = 15},
    ["seat26"] = {title = "S'asseoir 24", category = "main", animDict = "switch@trevor@pushes_bodybuilder", animName = "001426_03_trvs_5_pushes_bodybuilder_idle_bb2", animFlag = 15},
    ["seat25"] = {title = "S'asseoir 25", category = "main", animDict = "timetable@amanda@ig_7", animName = "base", animFlag = 15},
    ["seat26"] = {title = "S'asseoir 26", category = "main", animDict = "timetable@maid@couch@", animName = "base", animFlag = 15},
    ["seat27"] = {title = "S'asseoir 27", category = "main", animDict = "safe@franklin@ig_13", animName = "base", animFlag = 15},
    ["seat28"] = {title = "S'asseoir 28", category = "main", animDict = "timetable@reunited@ig_10", animName = "base_amanda", animFlag = 15},
    ["seat29"] = {title = "S'asseoir 29", category = "main", animDict = "timetable@reunited@ig_10", animName = "base_jimmy", animFlag = 15},
    ["seat30"] = {title = "S'asseoir 30", category = "main", animDict = "timetable@trevor@smoking_meth@base", animName = "base", animFlag = 15},
    ["seat31"] = {title = "S'asseoir 31", category = "main", animDict = "safe@franklin@ig_13", animName = "tv_base", animFlag = 15},
    ["seat32"] = {title = "S'asseoir 32", category = "main", animDict = "missheist_jewelleadinoutjh_endscene", animName = "loop_mic", animFlag = 15},
    ["seat33"] = {title = "S'asseoir 33", category = "main", animDict = "safe@michael@ig_3", animName = "base_michael", animFlag = 15},
    ["seat34"] = {title = "S'asseoir 34", category = "main", animDict = "anim@heists@heist_safehouse_intro@phone_couch@male", animName = "phone_couch_male_idle", animFlag = 15},
    ["seat35"] = {title = "S'asseoir 35", category = "main", animDict = "switch@michael@tv_w_kids", animName = "001520_02_mics3_14_tv_w_kids_exit_trc", animFlag = 15},
	["lean"] = {title = "Boire un café", category = "main", emote = "WORLD_HUMAN_LEANING"},
    ["checking"] = {title = "Examiner", category = "main", animDict = "random@train_tracks", animName = "idle_e", animFlag = 15},
    ["kneeling"] = {title = "S'agenouiller", category = "main", animDict = "misstrevor1", animName = "threaten_ortega_endloop_ort", animFlag = 15},
    ["crouch"] = {title = "S'accroupir 1", category = "main", animDict = "amb@world_human_bum_wash@male@low@idle_a", animName = "idle_a", animFlag = 15},
    ["crouch2"] = {title = "S'accroupir 2", category = "main", animDict = "misschinese2_crystalmaze", animName = "2int_loop_a_taotranslator", animFlag = 15},
    ["crouch3"] = {title = "S'accroupir 3", category = "main", animDict = "missheistdockssetup1ig_10@base", animName = "talk_pipe_base_worker1", animFlag = 15},
    ["crouch4"] = {title = "S'accroupir 4", category = "main", animDict = "mp_weapons_deal_sting", animName = "crackhead_bag_loop", animFlag = 15},
    ["crouch5"] = {title = "S'accroupir 5", category = "main", animDict = "anim@miss@low@fin@lamar@", animName = "idle", animFlag = 15},
    ["crouch6"] = {title = "S'accroupir 6", category = "main", animDict = "rcmextreme3", animName = "idle", animFlag = 15},
    ["crouch7"] = {title = "S'accroupir 7", category = "main", animDict = "amb@medic@standing@kneel@idle_a", animName = "idle_a", animFlag = 15},
    ["crouch8"] = {title = "S'accroupir 8", category = "main", animDict = "misstrevor2ron_basic_moves", animName = "idle", animFlag = 15},
    ["crouch9"] = {title = "S'accroupir 9", category = "main", animDict = "random@getawaydriver", animName = "base", animFlag = 15},
    ['lying'] = {title = "Couché 1", category = "main", emote = "PROP_HUMAN_SEAT_SUNLOUNGER"},
    ["lying2"] = {title = "Couché 2", category = "main", emote = "WORLD_HUMAN_SUNBATHE_BACK"},
    ["lying3"] = {title = "Couché 3", category = "main", animDict = "amb@world_human_picnic@male@base", animName = "base", animFlag = 15},
    ["lying4"] = {title = "Couché 4", category = "main", animDict = "amb@world_human_picnic@female@base", animName = "base", animFlag = 15},
    ["lying5"] = {title = "Couché 5", category = "main", animDict = "amb@world_human_sunbathe@male@front@base", animName = "base", animFlag = 15},
    ["lying6"] = {title = "Couché 6", category = "main", animDict = "switch@trevor@scares_tramp", animName = "trev_scares_tramp_idle_tramp", animFlag = 15},
    ["lying7"] = {title = "Couché 7", category = "main", emote = "WORLD_HUMAN_BUM_SLUMPED"},
    ["lying8"] = {title = "Couché 8", category = "main", animDict = "switch@trevor@annoys_sunbathers", animName = "trev_annoys_sunbathers_loop_girl", animFlag = 15},
    ["lying9"] = {title = "Couché 9", category = "main", animDict = "missfbi3_sniping", animName = "prone_dave", animFlag = 15},
    ["lying10"] = {title = "Couché 10", category = "main", animDict = "missheist_jewel", animName = "2b_guard_onfloor_loop", animFlag = 15},
    ["lying11"] = {title = "Couché 11", category = "main", animDict = "missheist_jewel", animName = "gassed_npc_guard", animFlag = 15},
    ["lying12"] = {title = "Couché 12", category = "main", animDict = "switch@trevor@annoys_sunbathers", animName = "trev_annoys_sunbathers_loop_girl", animFlag = 15},
    ["lying13"] = {title = "Couché 13", category = "main", animDict = "missfam5mcs_4leadin", animName = "family_5_mcs_4_loop_jimmy", animFlag = 15},
    ["lying14"] = {title = "Couché 14", category = "main", animDict = "amb@world_human_sunbathe@female@front@base", animName = "base", animFlag = 15},
    ["lying15"] = {title = "Couché 15", category = "main", animDict = "misssolomon_5@end", animName = "dead_black_ops", animFlag = 15},
    ["lying16"] = {title = "Couché 16", category = "main", animDict = "timetable@tracy@sleep@", animName = "base", animFlag = 15},
    ["lying17"] = {title = "Couché 17", category = "main", animDict = "random@dealgonewrong", animName = "base", animFlag = 15},
    ["lying18"] = {title = "Couché 18", category = "main", animDict = "switch@trevor@scares_tramp", animName = "trev_scares_tramp_idle_tramp", animFlag = 15},
    ["lying19"] = {title = "Couché 19", category = "main", animDict = "amb@world_human_bum_slumped@male@laying_on_right_side@base", animName = "base", animFlag = 15},
    ["lying20"] = {title = "Couché 20", category = "main", animDict = "timetable@ron@ig_3_couch", animName = "laying", animFlag = 15},
    ["homeless"] = {title = "Sdf", category = "main", emote = "WORLD_HUMAN_STUPOR"},
    ["phone"] = {title = "Téléphone", category = "main", emote = "WORLD_HUMAN_STAND_MOBILE"},
    ["camera"] = {title = "Caméra", category = "main", emote = "WORLD_HUMAN_PAPARAZZI"},
    ["medic"] = {title = "Médecin", category = "main", emote = "CODE_HUMAN_MEDIC_TEND_TO_DEAD"},
    ["damn"] = {title = "Mince", category = "main", animDict = "gestures@m@standing@casual", animName = "gesture_damn", animFlag = 50},
    ["facepalm"] = {title = "Oh mon dieux 1", category = "main", animDict = "anim@mp_player_intupperface_palm", animName = "idle_a", animFlag = 15},
    ["facepalm2"] = {title = "Oh mon dieux 2", category = "main", animDict = "anim@mp_player_intcelebrationfemale@face_palm", animName = "face_palm", animFlag = 49},
    ["facepalm3"] = {title = "Oh mon dieux 3", category = "main", animDict = "random@car_thief@agitated@idle_a", animName = "agitated_idle_a", animFlag = 15},
    ["facepalm4"] = {title = "Oh mon dieux 4", category = "main", animDict = "anim@mp_player_intcelebrationmale@face_palm", animName = "face_palm", animFlag = 15},
    ["handsup"] = {title = "Levez les mains", category = "main", animDict = "random@mugging3", animName = "handsup_standing_base", animFlag = 49},
    ["elbow"] = {title = "Otage", category = "main", animDict = "anim@amb@code_human_in_car_idles@arm@generic@ds@base", animName = "idle", animFlag = 49},
    ["aiming"] = {title = "Visée 1", category = "main", animDict = "combat@aim_variations@1h@gang", animName = "aim_variation_a", animFlag = 49},
    ["aiming2"] = {title = "Visée 2", category = "main", animDict = "combat@aim_variations@1h@gang", animName = "aim_variation_a", animFlag = 49},
	["talk"] = { title = "Parler 1", category = "stand", emote = "WORLD_HUMAN_HANG_OUT_STREET"},
	["talk2"] = { title = "Parler 2", category = "stand", animDict = "missfbi3_party_b", animName = "talk_inside_loop_male1", animFlag = 15},
	["talk3"] = { title = "Parler 3", category = "stand", animDict = "missfbi3_party_b", animName = "talk_balcony_loop_male1", animFlag = 15},
	["talk4"] = { title = "Parler 4", category = "stand", animDict = "anim@heists@prison_heist", animName = "ped_a_loop_a", animFlag = 15},
	["talk5"] = { title = "Parler 5", category = "stand", animDict = "misscarsteal4@actor", animName = "actor_berating_assistant", animFlag = 49},
  ["standing1"] = {title = "Debout 1", category = "stand", animDict = "amb@world_human_prostitute@crackhooker@base", animName = "base", animFlag = 15},
  ["standing2"] = {title = "Debout 2", category = "stand", animDict = "amb@world_human_leaning@female@wall@back@holding_elbow@base", animName = "base", animFlag = 15},
  ["standing3"] = {title = "Debout 3", category = "stand", animDict = "mp_move@prostitute@m@cokehead", animName = "idle", animFlag = 15},
  ["standing4"] = {title = "Debout 4", category = "stand", animDict = "oddjobs@taxi@argument", animName = "hooker_loop_a_hooker_b", animFlag = 15},
  ["standing5"] = {title = "Debout 5", category = "stand", animDict = "oddjobs@taxi@argument", animName = "hooker_loop_a_hooker_a", animFlag = 15},
	["bodyguard"] = { title = "Garde du corps", category = "stand", emote = "WORLD_HUMAN_GUARD_STAND"},
	["hands"] = { title = "Mains 1", category = "stand", animDict = "amb@world_human_hang_out_street@female_arms_crossed@base", animName = "base", animFlag = 50},
	["hands2"] = { title = "Mains 2", category = "stand", animDict = "anim@miss@low@fin@vagos@", animName = "idle_ped06", animFlag = 50},
	["hands3"] = { title = "Mains 3", category = "stand", animDict = "amb@code_human_police_investigate@base", animName = "base", animFlag = 50},
	["hands4"] = { title = "Mains 4", category = "stand", animDict = "anim@heists@heist_corona@single_team", animName = "single_team_intro_boss", animFlag = 15},
	["hands5"] = { title = "Mains 5", category = "stand", animDict = "anim@amb@nightclub@peds@", animName = "rcmme_amanda1_stand_loop_cop", animFlag = 50},
  ["belt"] = {title = "Ceinture", category = "stand", animDict = "amb@world_human_cop_idles@male@base", animName = "base", animFlag = 15},
	["proud"] = { title = "Fière", category = "stand", animDict = "rcmbarry", animName = "base", animFlag = 49},
	["bras"] = { title = "David Kravmaga", category = "stand", animDict = "anim@arena@celeb@flat@solo@no_props@", animName = "flip_a_player_a", animFlag = 7},
	["bras"] = { title = "Chercher preuves au sol (police)", category = "stand", animDict = "amb@medic@standing@kneel@base", animName = "base", animFlag = 6},
	["bras"] = { title = "Bras tendu", category = "stand", animDict = "nm@hands", animName = "flail", animFlag = 5},
	["blessure1"] = { title = "Blessure à l'épaule droite", category = "stand", animDict = "anim@miss@low@fin@vagos@", animName = "idle_ped06", animFlag = 4},
	["bbq2"] = { title = "BBQ 2", category = "stand", animDict = "amb@prop_human_bbq@male@idle_a", animName = "idle_c", animFlag = 3},
	["bbq1"] = { title = "BBQ 1", category = "stand", animDict = "amb@prop_human_bbq@male@idle_b", animName = "idle_d", animFlag = 2},
  ["acrobatie"] = {title = "Acrobatie 1", category = "stand", animDict = "anim@arena@celeb@flat@solo@no_props@", animName = "cap_a_player_a", animFlag = 1},
  ["holdcap"] = {title = "Oh mon dieux !", category = "stand", animDict = "perlenfuchs@hold_cap", animName = "hold_cap_clip", animFlag = 15},
  ["bangbang"] = {title = "Pan Pan !", category = "stand", animDict = "anim@mp_player_intcelebrationfemale@bang_bang", animName = "bang_bang", animFlag = 15},
  ["jcarlowrider"] = {title = "Style Voiture Lowrider", category = "stand", animDict = "anim@veh@lowrider@low@front_ds@arm@base", animName = "sit", animFlag = 50},

	["fear"] = {title = "Craindre 1", category = "help", animDict = "amb@code_human_cower_stand@female@idle_a", animName = "idle_c", animFlag = 15},
	["fear2"] = {title = "Craindre 2", category = "help", animDict = "anim@heists@ornate_bank@hostages@cashier_a@", animName = "idle", animFlag = 15},
	["fear3"] = {title = "Craindre 3", category = "help", animDict = "rcmtmom_2leadinout", animName = "tmom_2_leadout_loop", animFlag = 15},
	["injured"] = {title = "Blessé 1", category = "help", animDict = "anim@heists@prison_heistig_5_p1_rashkovsky_idle", animName = "idle_180", animFlag = 15},
	["injured2"] = {title = "Blessé 2", category = "help", animDict = "combat@damage@writheidle_a", animName = "writhe_idle_a", animFlag = 15},
	["injured3"] = {title = "Blessé 3", category = "help", animDict = "random@dealgonewrong", animName = "idle_b", animFlag = 15},
	["fall"] = {title = "Tombe  1", category = "help", animDict = "dam_ko@shot", animName = "ko_back_01", animFlag = 15},
	["fall2"] = {title = "Tombe 2", category = "help", animDict = "random@drunk_driver_1", animName = "drunk_fall_over", animFlag = 14},
	["fall3"] = {title = "Ne me tuer", category = "help", animDict = "anim@gangops@hostage@", animName = "victim_fail", animFlag = 14},
	["jdontkillme"] = {title = "Ne me tue pas !", category = "help", animDict = "missheist_jewel", animName = "manageress_kneel_loop", animFlag = 14},
	["unconscious"] = {title = "Inconscient 1", category = "help", animDict = "missarmenian2", animName = "drunk_loop", animFlag = 15},
	["unconscious2"] = {title = "Inconscient 2", category = "help", animDict = "misslamar1dead_body", animName = "dead_idle", animFlag = 15},
	["unconscious3"] = {title = "Inconscient 3", category = "help", animDict = "move_injured_ground", animName = "front_loop", animFlag = 15},
	["surrender"] = {title = "Abandonner 1", category = "help", animDict = "random@mugging3", animName = "handsup_standing_base", animFlag = 49},
	["surrender2"] = {title = "Abandonner 2", category = "help", animDict = "random@arrests@busted", animName = "idle_a", animFlag = 49},
  ["surrender3"] = {title = "Abandonner 3", category = "help", animDict = "misschinese2_crystalmaze", animName = "_stand_loop", animFlag = 49},
  ["crying"] = {title = "Pleurer 1", category = "help", animDict = "mp_bank_heist_1", animName = "f_cower_01", animFlag = 15},
  ["crying2"] = {title = "Pleurer 2", category = "help", animDict = "random@domestic", animName = "f_attack_end", animFlag = 50},
  ["crying3"] = {title = "Pleurer 3", category = "help", animDict = "random@robbery", animName = "f_cower_01", animFlag = 15},

  ["breakdance"] = {title = "Robot", category = "party", animDict = "export@breakdance", animName = "breakdance"},
  ["electroshuffle"] = {title = "Electro Shuffle", category = "party", animDict = "custom@electroshuffle_original", animName = "electroshuffle_original"},
  ["floss"] = {title = "Floss", category = "party", animDict = "custom@floss", animName = "floss", animFlag = 15},
  ["jdrill1"] = {title = "Drill", category = "party", animDict = "anim@amb@nightclub@mini@dance@dance_solo@shuffle@", animName = "high_left_down"},
  ["jdrill2"] = {title = "Drill 2", category = "party", animDict = "anim@amb@nightclub@mini@dance@dance_solo@shuffle@", animName = "high_center"},
  ["jdrill3"] = {title = "Drill 3", category = "party", animDict = "anim@amb@nightclub@mini@dance@dance_solo@shuffle@", animName = "high_right_down"},
  ["blixkytwirl2"] = {title = "Blixky Twirl", category = "party", animDict = "div@woowalk@test", animName = "blixkytwirl2"},
  ["dab"] = {title = "Dab", category = "party", animDict = "custom@dab", animName = "dab"},
  ["dancedrink"] = {title = "Danser avec une bière", category = "party", animDict = "anim@amb@nightclub_island@dancers@beachdanceprop@", animName = "mi_idle_c_m01", bone = 28422, prop = "prop_beer_amopen", propPos = {0.0, 0.0, 0.0, 0.0, 0.0, 20.0}, animFlag = 15},
  ["dancedrink2"] = {title = "Danser avec un verre de vin", category = "party", animDict = "anim@amb@nightclub_island@dancers@beachdanceprop@", animName = "mi_loop_f1", bone = 28422, prop = "p_wine_glass_s", propPos = {0.0, 0.0, -0.0900, 0.0, 0.0, 0.0}, animFlag = 15},
  ["dancedrink3"] = {title = "Danser avec une bouteille de whisky", category = "party", animDict = "anim@amb@nightclub_island@dancers@beachdanceprop@", animName = "mi_loop_m04", bone = 28422, prop = "ba_prop_battle_whiskey_opaque_s", propPos = {-0.0100, 0.0, 0.0, 0.0, 0.0, 10.0}, animFlag = 15},

	["hiphop3"] = {title = "Break Dance", category = "party", animDict = "custom@hiphop3", animName = "hiphop3"},
	["divbdance11"] = {title = "Break Dance 2", category = "party", animDict = "divined@breakdances@new", animName = "divbdance11"},
	["divbdance12"] = {title = "Break Dance 3", category = "party", animDict = "divined@breakdances@new", animName = "divbdance12"},
	["divbdance7"] = {title = "Break Dance 4", category = "party", animDict = "divined@breakdances@new", animName = "divbdance7"},
	["divbdance8"] = {title = "Break Dance 5", category = "party", animDict = "divined@breakdances@new", animName = "divbdance8"},


	["flex"] = {title = "S'étirer", category = "sport", emote = "WORLD_HUMAN_MUSCLE_FLEX"},
	["pushups"] = {title = "Pompe", category = "sport", animDict = "amb@world_human_push_ups@male@idle_a", animName = "idle_d", animFlag = 15},
	["crunches"] = {title = "Abdo", category = "sport", animDict = "amb@world_human_sit_ups@male@idle_a", animName = "idle_a", animFlag = 15},
	["joga"] = {title = "Yoga", category = "sport", emote = "WORLD_HUMAN_YOGA"},
  ["joga2"] = {title = "Yoga 2", category = "sport", animDict = "timetable@amanda@ig_4", animName = "ig_4_idle", animFlag = 15},
	["meditation"] = {title = "Méditer 1", category = "sport", animDict = "rcmcollect_paperleadinout@", animName = "meditiate_idle", animFlag = 15},
	["meditation2"] = {title = "Méditer 2", category = "sport", animDict = "rcmepsilonism3", animName = "ep_3_rcm_marnie_meditating", animFlag = 15},
  ["meditation3"] = {title = "Méditer 3", category = "sport", animDict = "misscarsteal1leadin", animName = "devon_idle_02", animFlag = 15},
	["jogging"] = {title = "Jogging 1", category = "sport", animDict = "amb@world_human_jog_standing@male@idle_a", animName = "idle_a", animFlag = 15},
	["jogging2"] = {title = "Jogging 2", category = "sport", animDict = "amb@world_human_jog_standing@female@idle_a", animName = "idle_a", animFlag = 15},
	["puppy"] = {title = "Puppy", category = "sport", animDict = "timetable@reunited@ig_2", animName = "jimmy_getknocked", animFlag = 15},
	["warmingup"] = {title = "Échauffement 1", category = "sport", animDict = "anim@amb@clubhouse@mini@arm_wrestling@", animName = "stand_idle_a", animFlag = 15},
	["warmingup2"] = {title = "Échauffement 2", category = "sport", animDict = "mini@triathlon", animName = "ig_2_gen_warmup_02", animFlag = 15},
	["warmingup3"] = {title = "Échauffement 3", category = "sport", animDict = "mini@triathlon", animName = "ig_2_gen_warmup_01", animFlag = 15},
	["warmingup4"] = {title = "Échauffement 4", category = "sport", animDict = "rcmfanatic1maryann_stretchidle_b", animName = "idle_e", animFlag = 15},
  ["warmingup5"] = {title = "Échauffement 5", category = "sport", animDict = "switch@franklin@gang_taunt_p1", animName = "gang_taunt_loop_thug_02", animFlag = 15},
	["tired"] = {title = "Fatigué 1", category = "sport", animDict = "mini@triathlon", animName = "jog_idle_e", animFlag = 15},
	["tired2"] = {title = "Fatigué 2", category = "sport", animDict = "re@construction", animName = "out_of_breath", animFlag = 15},
  ["tired3"] = {title = "Fatigué 3", category = "sport", animDict = "misscarsteal2pimpsex", animName = "shagloop_pimp", animFlag = 15},
  ["tired4"] = {title = "Fatigué 4", category = "sport", animDict = "timetable@reunited@ig_2", animName = "jimmy_base", animFlag = 15},
	["fists"] = {title = "Fists", category = "sport", animDict = "anim@mp_player_intcelebrationfemale@knuckle_crunch", animName = "knuckle_crunch", animFlag = 49},
	["cheering"] = {title = "Applaudissement 1", category = "sport", emote = "WORLD_HUMAN_CHEERING"},
	["cheering2"] = {title = "Applaudissement 2", category = "sport", animDict = "anim@amb@nightclub@peds@", animName = "amb_world_human_cheering_female_c", animFlag = 15},
	["cheering3"] = {title = "Applaudissement 3", category = "sport", animDict = "anim@arena@celeb@flat@solo@no_props@", animName = "angry_clap_a_player_a", animFlag = 15},
  ["cheering4"] = {title = "Applaudissement 4", category = "sport", animDict = "amb@world_human_cheering@female_a", animName = "base", animFlag = 15},
  ["cheering5"] = {title = "Applaudissement 5", category = "sport", animDict = "amb@world_human_cheering@female_d", animName = "base", animFlag = 15},
  ["cheering6"] = {title = "Applaudissement 6", category = "sport", animDict = "missfbi3_sniping", animName = "male_unarmed_a", animFlag = 15},
	["goalcelebration"] = {title = "Célébration des buts 1", category = "sport", animDict = "anim@arena@celeb@flat@solo@no_props@", animName = "slide_a_player_a", animFlag = 0},
	["goalcelebration2"] = {title = "Célébration des buts 2", category = "sport", animDict = "anim@arena@celeb@flat@solo@no_props@", animName = "slide_b_player_a", animFlag = 0},
	["goalcelebration3"] = {title = "Célébration des buts 3", category = "sport", animDict = "anim@arena@celeb@flat@solo@no_props@", animName = "slide_c_player_a", animFlag = 0},
	["goalcelebration4"] = {title = "Célébration des buts 4", category = "sport", animDict = "anim@arena@celeb@flat@solo@no_props@", animName = "slugger_a_player_a", animFlag = 0},
	["goalcelebration5"] = {title = "Célébration des buts 5", category = "sport", animDict = "rcmfanatic1celebrate", animName = "celebrate", animFlag = 0},
	["goalcelebration6"] = {title = "Célébration des buts 6", category = "sport", animDict = "rcmbarry", animName = "mind_control_b_loop", animFlag = 15},
	["flip"] = {title = "Retourner 1", category = "sport", animDict = "anim@arena@celeb@flat@solo@no_props@", animName = "cap_a_player_a", animFlag = 0},
	["flip2"] = {title = "Retourner 2", category = "sport", animDict = "anim@arena@celeb@flat@solo@no_props@", animName = "flip_a_player_a", animFlag = 0},
	["countdown"] = {title = "Compte à rebours", category = "sport", animDict = "random@street_race", animName = "grid_girl_race_start", animFlag = 14},

  ["repairing"] = {title = "Réparation", category = "other", animDict = "misscarsteal2pervert", animName = "pervert_husband", animFlag = 15},
  ["repairing2"] = {title = "Réparation 2", category = "other", animDict = "missmechanic", animName = "work_base", animFlag = 15},
  ["repairing3"] = {title = "Réparation 3", category = "bang", animDict = "amb@prop_human_movie_bulb@base", animName = "base", animFlag = 15},
  ["wagging"] = {title = "Remuer", category = "other", animDict = "gestures@m@car@std@casual@ps", animName = "gesture_displeased", animFlag = 15},
  ["shower"] = {title = "Douche", category = "other", animDict = "mp_safehouseshower@female@", animName = "shower_idle_a", animFlag = 15},
  ["freak"] = {title = "Anormal", category = "other", animDict = "anim@mp_player_intcelebrationmale@surrender", animName = "surrender", animFlag = 15},
  ["freak2"] = {title = "Anormal 2", category = "other", animDict = "anim@mp_player_intcelebrationmale@thumb_on_ears", animName = "thumb_on_ears", animFlag = 15},
  ["telescope"] = {title = "Telescope", category = "other", animDict = "mini@telescope", animName = "idle", animFlag = 15},
  ["telescope2"] = {title = "Telescope 2", category = "other", animDict = "mini@telescope", animName = "public_idle", animFlag = 15},
  ["puking"] = {title = "Vomir", category = "other", animDict = "timetable@tracy@ig_7@idle_a", animName = "idle_a", animFlag = 15},
  ["piss"] = {title = "Pisser", category = "other", animDict = "rcm_epsilonism4", animName = "peeing", animFlag = 15},
  ["looking"] = {title = "Regarder", category = "other", animDict = "oddjobs@basejump@", animName = "ped_d_loop", animFlag = 15},
  ["lifting"] = {title = "Ramasser 1", category = "other", animDict = "anim@mp_snowball", animName = "pickup_snowball", animFlag = 15},
  ["lifting2"] = {title = "Ramasser 2", category = "other", animDict = "combat@drag_ped@", animName = "injured_pickup_back_plyr", animFlag = 15},
  ["lifting3"] = {title = "Ramasser 3", category = "other", animDict = "missheist_agency2aig_13", animName = "pickup_briefcase", animFlag = 15},
  ["grace"] = {title = "Grace", category = "other", animDict = "misscarsteal4@actor", animName = "actor_warming_up_loop_1", animFlag = 15},
  ["grace2"] = {title = "Grace 2", category = "other", animDict = "misscarsteal4@actor", animName = "actor_warming_up_loop_2", animFlag = 15},
  ["grace3"] = {title = "Grace 3", category = "other", animDict = "misscarsteal4@actor", animName = "actor_warming_up_loop_3", animFlag = 15},
  ["grace4"] = {title = "Grace 4", category = "other", animDict = "misscarsteal4@actor", animName = "actor_warming_up_loop_4", animFlag = 15},
  ["kicking"] = {title = "Kicking", category = "other", animDict = "missheistdockssetup1ig_13@kick_idle", animName = "guard_beatup_kickidle_guard1", animFlag = 15},
  ["kicking2"] = {title = "Coups de pied 2", category = "other", animDict = "missheistdockssetup1ig_13@kick_idle", animName = "guard_beatup_kickidle_guard2", animFlag = 15},
  ["kicking3"] = {title = "Coups de pied 3", category = "other", animDict = "melee@knife@streamed_variations", animName = "ground_attack_on_spot_var_a", animFlag = 15},
  ["massage"] = {title = "Massage", category = "other", animDict = "missheistdocks2bleadinoutlsdh_2b_int", animName = "leg_massage_b_floyd", animFlag = 15},
  ["massage2"] = {title = "Massage 2", category = "other", animDict = "missheistdocks2bleadinoutlsdh_2b_int", animName = "leg_massage_floyd", animFlag = 15},
  ["massage3"] = {title = "Massage 3", category = "other", animDict = "timetable@patricia@pat_ig_2@base", animName = "base", animFlag = 15},
	["race"] = {title = "Course", category = "other", animDict = "random@street_race", animName = "grid_girl_race_start", animFlag = 1},
  ["race2"] = {title = "Course 2", category = "other", animDict = "special_ped@jane@franklin_1@franklin_1f", animName = "everythingisup_5", animFlag = 15},
	["slowclap"] = {title = "Battement lent 1", category = "other", animDict = "anim@mp_player_intcelebrationmale@slow_clap", animName = "slow_clap", animFlag = 49},
	["slowclap2"] = {title = "Battement lent 2", category = "other", animDict = "anim@mp_player_intcelebrationfemale@slow_clap", animName = "slow_clap", animFlag = 49},
  ["clap"] = {title = "Clap", category = "other", animDict = "anim@mp_player_intupperslow_clap", animName = "idle_a", animFlag = 15},
	["kiss"] = {title = "Baiser 1", category = "other", animDict = "anim@mp_player_intcelebrationfemale@blow_kiss", animName = "blow_kiss", animFlag = 0},
	["kiss2"] = {title = "Baiser 2", category = "other", animDict = "anim@mp_player_intcelebrationfemale@finger_kiss", animName = "finger_kiss", animFlag = 0},
	["shhh"] = {title = "Shhh 1", category = "other", animDict = "anim@mp_player_intuppershush", animName = "idle_a_fp", animFlag = 50},
	["shhh2"] = {title = "Shhh 2", category = "other", animDict = "anim@arena@celeb@flat@solo@no_props@", animName = "giggle_a_player_b", animFlag = 0},
	["counting"] = {title = "Compte", category = "other", animDict = "rcmjosh4", animName = "beckon_a_cop_a", animFlag = 50},
	["dustingoff"] = {title = "Dépoussiérer", category = "other", animDict = "move_m@_idles@shake_off", animName = "shakeoff_1", animFlag = 15},
	["washing"] = {title = "Laver", category = "other",  emote = "WORLD_HUMAN_BUM_WASH"},
	["pullingout"] = {title = "Tirer", category = "other", animDict = "anim@amb@business@coc@coc_unpack_cut@", animName = "fullcut_cycle_v1_cokepacker", animFlag = 15},
	["collecting"] = {title = "Collecté", category = "other", animDict = "anim@heists@money_grab@duffel", animName = "loop", animFlag = 15},
	["scratch"] = {title = "Gratter 1", category = "other", animDict = "missarmenian2", animName = "arm2_lamar_idle_01", animFlag = 15},
	["scratch2"] = {title = "Gratter 2", category = "other", animDict = "anim@mp_freemode_return@f@idle", animName = "idle_a", animFlag = 15},
	["scratch3"] = {title = "Gratter 3", category = "other", animDict = "anim@amb@machinery@speed_drill@", animName = "scratch_amy_skater_01", animFlag = 0},
	["sniffing"] = {title = "Renifler", category = "other", animDict = "move_p_m_two_idles@generic", animName = "fidget_sniff_fingers", animFlag = 15},
	["Sneezing"] = {title = "Eternuement", category = "other", animDict = "timetable@gardener@smoking_joint", animName = "idle_coug", animFlag = 15},
	["salut"] = {title = "Salut", category = "other", animDict = "mp_player_int_uppersalute", animName = "mp_player_int_salute", animFlag = 50},
	["cnsk"] = {title = "Bien 1", category = "other", animDict = "misscommon@response", animName = "bring_it_on", animFlag = 0},
	["cnsk2"] = {title = "Bien 2", category = "other", animDict = "missexile3@trevor_idle@base", animName = "base", animFlag = 15},
	["cnsk3"] = {title = "Bien 3", category = "other", animDict = "mini@triathlon", animName = "want_some_of_this", animFlag = 0},
	["tc"] = {title = "Trou du cul", category = "other", animDict = "misscommon@response", animName = "screw_you", animFlag = 0},
	["fucku"] = {title = "Va te faire foutre 1", category = "other", animDict = "anim@mp_player_intselfiethe_bird", animName = "idle_a", animFlag = 50},
	["fucku2"] = {title = "Va te faire foutre 2", category = "other", animDict = "mp_player_int_upperfinger", animName = "mp_player_int_finger_02_enter", animFlag = 50},
	["fucku3"] = {title = "Va te faire foutre 3", category = "other", animDict = "anim@mp_player_intcelebrationfemale@finger", animName = "finger", animFlag = 50},
	["fucku4"] = {title = "Va te faire foutre 4", category = "other", animDict = "anim@mp_player_intcelebrationmale@finger", animName = "finger", animFlag = 0},
	["fucku5"] = {title = "Va te faire foutre 5", category = "other", animDict = "anim@arena@celeb@podium@no_prop@", animName = "flip_off_a_1st", animFlag = 0},
	["fucku6"] = {title = "Va te faire foutre 6", category = "other", animDict = "anim@arena@celeb@podium@no_prop@", animName = "flip_off_c_1st", animFlag = 0},
	["head"] = {title = "Tête", category = "other", animDict = "melee@unarmed@streamed_variations", animName = "plyr_takedown_front_headbutt", animFlag = 0},
	["toe"] = {title = "Dans ton cul 1", category = "other", animDict = "anim@mp_player_intcelebrationfemale@dock", animName = "dock", animFlag = 0},
	["toe2"] = {title = "Dans ton cul 2", category = "other", animDict = "anim@mp_player_intselfiedock", animName = "idle_a", animFlag = 49},
	["thumb"] = {title = "Pouce en l'air 1", category = "other", animDict = "anim@mp_player_intincarthumbs_uplow@ds@", animName = "idle_a", animFlag = 50},
	["thumb2"] = {title = "Pouce en l'air 2", category = "other", animDict = "mp_action", animName = "thanks_male_06", animFlag = 0},
	["thumb3"] = {title = "Pouce en l'air 3", category = "other", animDict = "random@hitch_lift", animName = "idle_f", animFlag = 49},
  ["thumb4"] = {title = "Pouce en l'air 4", category = "other", animDict = "anim@mp_player_intcelebrationmale@thumbs_up", animName = "thumbs_up", animFlag = 15},
	["no"] = {title = "Non 1", category = "other", animDict = "anim@heists@ornate_bank@chat_manager", animName = "fail", animFlag = 0},
	["no2"] = {title = "Non 2", category = "other", animDict = "anim@mp_player_intcelebrationfemale@no_way", animName = "no_way", animFlag = 0},
	["no3"] = {title = "Non 3", category = "other", animDict = "mini@triathlon", animName = "u_cant_do_that", animFlag = 0},
	["no4"] = {title = "Non 4", category = "other", animDict = "friends@frj@ig_1", animName = "wave_d", animFlag = 0},
  ["no5"] = {title = "Non 5", category = "other", animDict = "anim@mp_player_intcelebrationmale@no_way", animName = "no_way", animFlag = 15},
	["wave"] = {title = "Agiter 1", category = "other", animDict = "random@mugging5", animName = "001445_01_gangintimidation_1_female_idle_b", animFlag = 49},
	["wave2"] = {title = "Agiter 2", category = "other", animDict = "friends@fra@ig_1", animName = "over_here_idle_a", animFlag = 49},
	["wave3"] = {title = "Agiter 3", category = "other", animDict = "friends@frj@ig_1", animName = "wave_b", animFlag = 49},
	["wave4"] = {title = "Agiter 4", category = "other", animDict = "friends@frj@ig_1", animName = "wave_e", animFlag = 49},
	["wave5"] = {title = "Agiter 5", category = "other", animDict = "anim@amb@waving@female", animName = "ground_wave", animFlag = 49},
  ["wave6"] = {title = "Agiter 6", category = "other", animDict = "random@prisoner_lift", animName = "arms_waving", animFlag = 49},
  ["wave7"] = {title = "Agiter 7", category = "other", animDict = "random@hitch_lift", animName = "001445_01_gangintimidation_1_female_idle_b", animFlag = 15},
  ["wave8"] = {title = "Agiter 8", category = "other", animDict = "random@hitch_lift", animName = "carjack_mainloop_female", animFlag = 15},
  ["wave9"] = {title = "Agiter 9", category = "other", animDict = "random@hitch_lift", animName = "come_here_idle_c", animFlag = 15},
  ["wave10"] = {title = "Agiter 10", category = "other", animDict = "anim@mp_player_intcelebrationmale@wave", animName = "wave", animFlag = 15},
	["whistling"] = {title = "Sifflement 1", category = "other", animDict = "taxi_hail", animName = "hail_taxi", animFlag = 0},
	["whistling2"] = {title = "Sifflement 2", category = "other", animDict = "rcmnigel1c", animName = "hailing_whistle_waive_a", animFlag = 0},
	["glut"] = {title = "Rassasier", category = "other", animDict = "anim@mp_player_intcelebrationfemale@nose_pick", animName = "nose_pick", animFlag = 0},
	["kasa"] = {title = "Echouer", category = "other", animDict = "anim@mp_player_intcelebrationfemale@raining_cash", animName = "raining_cash", animFlag = 0},
	["dislodging"] = {title = "Délogement 1", category = "other", animDict = "switch@trevor@mocks_lapdance", animName = "001443_01_trvs_28_idle_stripper", animFlag = 15},
	["dislodging2"] = {title = "Délogement 2", category = "other", animDict = "mini@hookers_sp", animName = "ilde_c", animFlag = 15},
	["dislodging3"] = {title = "Délogement 3", category = "other", animDict = "random@street_race", animName = "_car_a_flirt_girl", animFlag = 0},
	["sweeping"] = {title = "Balayage", category = "other",  emote = "WORLD_HUMAN_JANITOR"},
	["flashlight"] = {title = "Lampe de poche", category = "other",  emote = "WORLD_HUMAN_SECURITY_SHINE_TORCH"},
	["baton"] = {title = "Bâton", category = "other",  emote = "WORLD_HUMAN_CAR_PARK_ATTENDANT"},
	["notebook2"] = {title = "Cahier 2", category = "other",  emote = "WORLD_HUMAN_CLIPBOARD"},
	["keyboard"] = {title = "Clavier 1", category = "other", animDict = "missheist_jewel@hacking", animName = "hack_loop", animFlag = 15},
	["keyboard2"] = {title = "Clavier 2", category = "other", animDict = "anim@heists@prison_heiststation@cop_reactions", animName = "cop_b_idle", animFlag = 15},
	["keyboard3"] = {title = "Clavier 3", category = "other", animDict = "mp_prison_break", animName = "hack_loop", animFlag = 15},
	["keyboard4"] = {title = "Clavier 4", category = "other", animDict = "mp_fbi_heist", animName = "loop", animFlag = 15},
	["phone2"] = {title = "Téléphone 2", category = "other", animDict = "anim@amb@nightclub@peds@", animName = "amb_world_human_leaning_male_wall_back_mobile_idle_a", animFlag = 15},
	["search"] = {title = "Rechercher", category = "other", animDict = "missexile3", animName = "ex03_dingy_search_case_b_michael", animFlag = 15},
	["cooking"] = {title = "Cuisiner", category = "other",  emote = "prop_human_bbq"},
	["cleaning"] = {title = "Nettoyer", category = "other",  emote = "WORLD_HUMAN_MAID_CLEAN"},
  ["cleaning3"] = {title = "Nettoyer 3", category = "other", animDict = "switch@franklin@cleaning_car", animName = "001946_01_gc_fras_v2_ig_5_base", animFlag = 15},
	["hammer"] = {title = "Marteau", category = "other",  emote = "WORLD_HUMAN_HAMMERING"},
	["torch"] = {title = "Lampe Torche", category = "other",  emote = "WORLD_HUMAN_WELDING"},
	["mechanic"] = {title = "Mécano 1", category = "other", animDict = "amb@world_human_vehicle_mechanic@male@base", animName = "base", animFlag = 15},
	["mechanic2"] = {title = "Mécano 2", category = "other", animDict = "mini@repair", animName = "fixing_a_player", animFlag = 15},
	["mechanic3"] = {title = "Mécano 3", category = "other", animDict = "anim@amb@clubhouse@tutorial@bkr_tut_ig3@", animName = "machinic_loop_mechandplayer", animFlag = 15},
	["mechanic4"] = {title = "Mécano 4", category = "other", animDict = "missmechanic", animName = "work2_base", animFlag = 15},
	["mechanic5"] = {title = "Mécano 5", category = "other", animDict = "mini@repair", animName = "fixing_a_ped", animFlag = 15},
	["recording"] = {title = "Enregistrement", category = "other",  emote = "world_human_mobile_film_shocking"},
	["knocking"] = {title = "Cognement 1", category = "other", animDict = "timetable@jimmy@doorknock@", animName = "knockdoor_idle", animFlag = 15},
	["knocking2"] = {title = "Cognement 2", category = "other", animDict = "missheistfbi3b_ig7", animName = "lift_fibagent_loop", animFlag = 15},
  ["knocking3"] = {title = "Cognement 3", category = "main", animDict = "misscarsteal4@toilet", animName = "desperate_toilet_idle_b", animFlag = 15},
	["pulling"] = {title = "Tirer", category = "other", animDict = "random@mugging4", animName = "struggle_loop_b_thief", animFlag = 15},
	["swingingout"] = {title = "Se balancer", category = "other", animDict = "random@paparazzi@peek", animName = "left_peek_a", animFlag = 15},
	["statua"] = {title = "Statue", category = "other",  emote = "WORLD_HUMAN_HUMAN_STATUE"},
	["beggar"] = {title = "Gueux", category = "other",  emote = "WORLD_HUMAN_BUM_FREEWAY"},
	["map"] = {title = "Carte", category = "other",  emote = "WORLD_HUMAN_TOURIST_MAP"},
	["illumination"] = {title = "Éclairage", category = "other", animDict = "anim@mp_player_intincardancebodhi@ds@", animName = "idle_a_fp", animFlag = 15},
	["praying"] = {title = "Prier", category = "other", animDict = "timetable@amanda@ig_4", animName = "ig_4_base", animFlag = 49},
	["corpse"] = {title = "Cadavre", category = "other", animDict = "anim@gangops@morgue@table@", animName = "body_search", animFlag = 15},
	["corpse2"] = {title = "Cadavre 2", category = "other", animDict = "mini@cpr@char_b@cpr_str", animName = "cpr_kol", animFlag = 15},
  ["cpr"] = {title = "CPR", category = "other", animDict = "mini@cpr@char_a@cpr_def", animName = "cpr_intro", animFlag = 15},
  ["cpr2"] = {title = "CPR 2", category = "other", animDict = "mini@cpr@char_a@cpr_str", animName = "cpr_kol", animFlag = 15},
	["chicken"] = {title = "Poulet", category = "other", animDict = "anim@mp_player_intcelebrationfemale@chicken_taunt", animName = "chicken_taunt", animFlag = 0},
	["dj"] = {title = "Dj 1", category = "other", animDict = "anim@mp_player_intcelebrationfemale@dj", animName = "dj", animFlag = 15},
	["dj2"] = {title = "Dj 2", category = "other", animDict = "anim@amb@nightclub@djs@dixon@", animName = "dixn_dance_cntr_open_dix", animFlag = 15},
  ["pointing"] = {title = "Pointing", category = "other", animDict = "oddjobs@suicide", animName = "bystander_pointinto", animFlag = 15},
  ["pointing2"] = {title = "Montrer du doigt 2", category = "other", animDict = "oddjobs@basejump@", animName = "ped_a_loop", animFlag = 15},
  ["pointing3"] = {title = "Montrer du doigt 3", category = "other", animDict = "missheist_agency2aig_1", animName = "direct_traffic_a", animFlag = 15},
  ["pointing4"] = {title = "Montrer du doigt 4", category = "other", animDict = "missheist_agency2aig_1", animName = "direct_traffic_b", animFlag = 15},
  ["pointing5"] = {title = "Montrer du doigt 5", category = "other", animDict = "missheist_agency2aig_1", animName = "direct_traffic_c", animFlag = 15},
  ["pointing6"] = {title = "Montrer du doigt 6", category = "other", animDict = "missheist_agency2aig_1", animName = "direct_traffic_d", animFlag = 15},
	["resist"] = {title = "Résister 1", category = "other", animDict = "anim@arena@prize_wheel@male", animName = "idle_spinning", animFlag = 15},
	["resist2"] = {title = "Résister 2", category = "other", animDict = "anim@amb@clubhouse@bar@drink@idle_a", animName = "idle_a_bartender", animFlag = 15},
	["resist3"] = {title = "Résister 3", category = "other", animDict = "amb@prop_human_bum_shopping_cart@male@idle_a", animName = "idle_c", animFlag = 15},
	["resist4"] = {title = "Résister 4", category = "other", animDict = "anim@amb@nightclub@lazlow@ig1_vip@", animName = "clubvip_base_laz", animFlag = 15},
	["resist5"] = {title = "Résister 5", category = "other", animDict = "anim@heists@prison_heist", animName = "ped_b_loop_a", animFlag = 15},
	["resist6"] = {title = "Résister 6", category = "other", animDict = "timetable@mime@01_gc", animName = "idle_a", animFlag = 15},
	["resist7"] = {title = "Résister 7", category = "other", animDict = "misscarstealfinale", animName = "packer_idle_1_trevor", animFlag = 15},
	["resist8"] = {title = "Résister 8", category = "other", animDict = "misscarstealfinalecar_5_ig_1", animName = "waitloop_lamar", animFlag = 15},
  ["resist9"] = {title = "Résister 9", category = "other", animDict = "amb@prop_human_bum_shopping_cart@male@idle_a", animName = "idle_a", animFlag = 15},
  ["resist10"] = {title = "Résister 10", category = "other", animDict = "amb@prop_human_bum_shopping_cart@male@idle_a", animName = "idle_b", animFlag = 15},
  ["resist11"] = {title = "Résister 11", category = "other", animDict = "mini@strip_club@drink@idle_a", animName = "idle_a_bartender", animFlag = 15},
  ["resist12"] = {title = "Résister 12", category = "other", animDict = "missheist_agency2aig_4", animName = "look_plan_a_worker1", animFlag = 15},
  ["resist13"] = {title = "Résister 13", category = "other", animDict = "switch@trevor@bar", animName = "loop_bartender", animFlag = 49},
  ["resist14"] = {title = "Résister 14", category = "other", animDict = "missheist_agency2aig_4", animName = "look_plan_b_worker2", animFlag = 15},
  ["resist15"] = {title = "Résister 15", category = "other", animDict = "safe@franklin@ig_9", animName = "base_drink", animFlag = 15},
  ["resist16"] = {title = "Résister 16", category = "other", animDict = "safe@michael@ig_1", animName = "fifth_shot_base", animFlag = 15},
  ["resist17"] = {title = "Résister 17", category = "other", animDict = "safe@trevor@ig_6", animName = "base_2_trevor", animFlag = 15},
  ["resist18"] = {title = "Résister 18", category = "other", animDict = "switch@michael@marina", animName = "loop", animFlag = 15},
  ["resist19"] = {title = "Résister 19", category = "other", animDict = "switch@michael@pier", animName = "pier_lean_smoke_idle", animFlag = 15},
  ["resist20"] = {title = "Résister 20", category = "other", animDict = "switch@michael@sitting_on_car_bonnet", animName = "sitting_on_car_bonnet_loop", animFlag = 15},
  ["resist21"] = {title = "Résister 21", category = "other", animDict = "special_ped@mime@base", animName = "base", animFlag = 15},
  ["resist22"] = {title = "Résister 22", category = "other", animDict = "anim@amb@clubhouse@bar@bartender@", animName = "base_bartender", animFlag = 15},
  ["resist23"] = {title = "Résister 23", category = "other", animDict = "anim@amb@clubhouse@bar@bartender@", animName = "idle_a_bartender", animFlag = 15},
  ["resist24"] = {title = "Résister 24", category = "other", animDict = "anim@amb@clubhouse@bar@bartender@", animName = "greeting_b_bartender", animFlag = 15},
  ["resist25"] = {title = "Résister 25", category = "other", animDict = "anim@amb@clubhouse@bar@bartender@", animName = "greeting_a_bartender", animFlag = 15},
  ["resist26"] = {title = "Résister 26", category = "other", animDict = "anim@mp_ferris_wheel", animName = "idle_a_player_one", animFlag = 15},
  ["resist27"] = {title = "Résister 27", category = "other", animDict = "anim@mp_ferris_wheel", animName = "idle_a_player_two", animFlag = 15},
  ["resist28"] = {title = "Résister 28", category = "other", animDict = "switch@trevor@rude_at_cafe", animName = "001218_03_trvs_23_rude_at_cafe_idle_trv", animFlag = 15},
  ["resist29"] = {title = "Résister 29", category = "other", animDict = "amb@world_human_leaning@male@wall@back@foot_up@idle_a", animName = "idle_a", animFlag = 15},
  ["resist30"] = {title = "Résister 30", category = "other", animDict = "mini@strip_club@leaning@base", animName = "base", animFlag = 15},
  ["resist31"] = {title = "Résister 31", category = "other", animDict = "missfbi3_party_b", animName = "talk_inside_loop_male2", animFlag = 15},
  ["resist32"] = {title = "Résister 32", category = "other", animDict = "switch@trevor@garbage_food", animName = "loop_trevor", animFlag = 15},
  ["resist34"] = {title = "Résister 33", category = "other", animDict = "misslester1aig_3exit", animName = "air_guitar_01_exitloop_b", animFlag = 15},
  ["resist34"] = {title = "Résister 34", category = "other", animDict = "misslester1aig_9", animName = "idle_sitting_pedb", animFlag = 15},
  ["resist35"] = {title = "Résister 35", category = "other", animDict = "missstrip_club_lean", animName = "player_lean_rail_loop", animFlag = 15},
  ["resist36"] = {title = "Résister 36", category = "other", animDict = "missfbi3_sniping", animName = "smoke_b", animFlag = 15},
  ["resist37"] = {title = "Résister 37", category = "other", animDict = "misscarsteal1leadin", animName = "molly_idle_03", animFlag = 15},
  ["resist38"] = {title = "Résister 38", category = "other", animDict = "misscarstealfinale", animName = "packer_idle_base_trevor", animFlag = 15},
  ["resist39"] = {title = "Résister 39", category = "other", animDict = "missheistdockssetup1showcar@base", animName = "base_1", animFlag = 15},
  ["resist40"] = {title = "Résister 40", category = "other", animDict = "misscarsteal2pimpsex", animName = "pimpsex_punter", animFlag = 15},
	["excitement"] = {title = "Excitation", category = "other", animDict = "anim@mp_player_intcelebrationfemale@freakout", "freakout", 15},
	["spray"] = {title = "Vaporisateur", category = "other", animDict = "switch@franklin@lamar_tagging_wall", "lamar_tagging_exit_loop_lamar", 15},
	["plane"] = {title = "Avion", category = "other", animDict = "missfbi1", animName = "ledge_loop", animFlag = 15},
	["clown"] = {title = "Clown 1", category = "other", animDict = "rcm_barry2", animName = "clown_idle_1", animFlag = 15},
	["clown2"] = {title = "Clown 2", category = "other", animDict = "rcm_barry2", animName = "clown_idle_3", animFlag = 15},
	["clown3"] = {title = "Clown 3", category = "other", animDict = "rcm_barry2", animName = "clown_idle_0", animFlag = 15},
	["wheelchair"] = {title = "Fauteuil roulant", category = "other", animDict = "missfinale_c2leadinoutfin_c_int", animName = "_leadin_loop2_lester", animFlag = 15},
  ["please"] = {title = "Svp", category = "other", animDict = "gestures@m@car@std@casual@ps", animName = "gesture_bring_it_on", animFlag = 14},
  ["bro"] = {title = "Frère", category = "other", animDict = "anim@mp_player_intcelebrationmale@bro_love", animName = "bro_love", animFlag = 15},
  ["humpbacked"] = {title = "Bossu", category = "other", animDict = "move_characters@lester@std", animName = "idle", animFlag = 49},
  ["chin"] = {title = "Menton", category = "other", animDict = "anim@mp_player_intcelebrationmale@chin_brush", animName = "chin_brush", animFlag = 15},
  ["fist"] = {title = "Poing", category = "other", animDict = "anim@mp_player_intupperknuckle_crunch", animName = "idle_a", animFlag = 49},
  ["excited"] = {title = "Excité", category = "other", animDict = "missfbi3_sniping", animName = "male_unarmed_b", animFlag = 15},
  ["relax"] = {title = "Relaxer", category = "other", animDict = "amb@code_human_police_crowd_control@idle_a", animName = "idle_a", animFlag = 15},
  ["relax2"] = {title = "Relaxer 2", category = "other", animDict = "gestures@m@car@std@casual@ps", animName = "gesture_easy_now", animFlag = 15},
  ["head2"] = {title = "Tête 2", category = "other", animDict = "misscarsteal4@actor", animName = "dazed_idle", animFlag = 50},
  ["glad"] = {title = "Content", category = "other", animDict = "gestures@m@car@std@casual@ps", animName = "gesture_pleased", animFlag = 15},
  ["hold"] = {title = "Tenir", category = "other", animDict = "switch@franklin@gang_taunt_p1", animName = "gang_taunt_loop_franklin", animFlag = 15},
  ["callme"] = {title = "Appelle-moi", category = "other", animDict = "anim@mp_player_intincarcall_mestd@rds@", animName = "idle_a", animFlag = 15},
  ["jazzhands"] = {title = "Mains de jazz", category = "other", animDict = "anim@mp_player_intcelebrationmale@jazz_hands", animName = "jazz_hands", animFlag = 15},
  ["refueling"] = {title = "Ravitaillement", category = "other", animDict = "weapons@misc@jerrycan@", animName = "fire", animFlag = 15},
  ["oneleg"] = {title = "Une jambe", category = "other", animDict = "misscarsteal2pimpsex", animName = "shagloop_hooker", animFlag = 15},
  ["guard"] = {title = "Hilt-garde", category = "other", animDict = "oddjobs@assassinate@multi@", animName = "react_big_variations_a", animFlag = 15},
  ["loco"] = {title = "Locomotive", category = "other", animDict = "anim@mp_player_intcelebrationmale@you_loco", animName = "you_loco", animFlag = 15},
  ["excited2"] = {title = "Excité 2", category = "other", animDict = "anim@mp_player_intcelebrationmale@air_shagging", animName = "air_shagging", animFlag = 15},
  ["powered"] = {title = "Alimenté", category = "other", animDict = "switch@franklin@gang_taunt_p1", animName = "gang_taunt_loop_thug_01", animFlag = 15},
  ["vsign"] = {title = "V Sign", category = "other", animDict = "anim@mp_player_intcelebrationmale@v_sign", animName = "v_sign", animFlag = 15},
  ["powered2"] = {title = "Alimenté 2", category = "other", animDict = "switch@franklin@gang_taunt_p1", animName = "gang_taunt_loop_lamar", animFlag = 15},
  ["toilet"] = {title = "Toilettes", category = "other", animDict = "timetable@tracy@ig_1@base", animName = "base", animFlag = 15},
  ["why"] = {title = "Pourquoi", category = "other", animDict = "gestures@m@car@std@casual@ps", animName = "gesture_why", animFlag = 15},

	["style_standard"] = {anim = "move_m@generic", title = "Style: Standard", category="style"},
	["style_lame"] = {anim = "move_m@injured", title = "Style: Boiteux ", category="style"},
	["style_lame2"] = {anim = "move_heist_lester", title = "Style: Boiteux 2", category="style"},
	["style_ladies"] = {anim = "move_f@generic", title = "Style: Femmes", category="style"},
	["style_ladies2"] = {anim = "move_f@sexy@a", title = "Style: Femmes 2", category="style"},
	["style_ladies3"] = {anim = "MOVE_F@FEMME@", title = "Style: Femmes 3", category="style"},
	["style_casual"] = {anim = "move_m@casual@a", title = "Style: Décontracté", category="style"},
	["style_casual2"] = {anim = "move_m@casual@b", title = "Style: Décontracté 2", category="style"},
	["style_casual3"] = {anim = "move_m@casual@c", title = "Style: Décontracté 3", category="style"},
	["style_professor"] = {anim = "move_m@business@c", title = "Style: Professeur", category="style"},
	["style_slow"] = {anim = "move_characters@Jimmy@slow@", title = "Style: Lent", category="style"},
	["style_slow2"] = {anim = "move_p_m_zero_slow", title = "Style: Lent 2", category="style"},
	["style_haste"] = {anim = "move_m@hurry@a", title = "Style: Accélérer", category="style"},
	["style_trot"] = {anim = "move_m@quick", title = "Style: Trot", category="style"},
	["style_sassy"] = {anim = "move_m@sassy", title = "Style: Impertinent", category="style"},
	["style_loose"] = {anim = "move_m@casual@e", title = "Style: Lâche", category="style"},
	["style_loose2"] = {anim = "move_m@casual@d", title = "Style: Lâche 2", category="style"},
	["style_loose3"] = {anim = "move_m@tough_guy@", title = "Style: Lâche 3", category="style"},
	["style_loose4"] = {anim = "move_m@hipster@a", title = "Style: Lâche 4", category="style"},
	["style_loose5"] = {anim = "move_m@bag", title = "Style: Lâche 5", category="style"},
	["style_sad"] = {anim = "move_m@sad@a", title = "Style: Triste", category="style"},
	["style_sad2"] = {anim = "move_m@gangster@var_f", title = "Style: Triste 2", category="style"},
	["style_depressed"] = {anim = "move_m@depressed@a", title = "Style: Dépressif", category="style"},
	["style_stiff"] = {anim = "move_m@business@a", title = "Style: Dur", category="style"},
	["style_belated"] = {anim = "move_m@casual@f", title = "Style: Tardif", category="style"},
	["style_nervous"] = {anim = "move_m@fire", title = "Style: Nerveux", category="style"},
	["style_nervous2"] = {anim = "move_m@hurry_butch@a", title = "Style: Nerveux 2", category="style"},
	["style_nervous3"] = {anim = "move_m@hurry_butch@b", title = "Style: Nerveux 3", category="style"},
	["style_freak"] = {anim = "move_m@hobo@a", title = "Style: Anormal", category="style"},
	["style_scared"] = {anim = "move_m@scared", title = "Style: Effrayé", category="style"},
	["style_cossack"] = {anim = "move_m@brave@a", title = "Style: Musclé", category="style"},
	["style_cossack2"] = {anim = "move_m@muscle@a", title = "Style: Musclé 2", category="style"},
	["style_cossack3"] = {anim = "move_m@intimidation@1h", title = "Style: Musclé 3", category="style"},
	["style_cossack4"] = {anim = "move_p_m_one", title = "Style: Musclé 4", category="style"},
	["style_gangster"] = {anim = "move_m@gangster@generic", title = "Style: Gangster", category="style"},
	["style_gangster2"] = {anim = "move_m@shadyped@a", title = "Style: Gangster 2", category="style"},
	["style_swag"] = {anim = "move_m@swagger", title = "Style: Swag", category="style"},
	["style_skinnyguy"] = {anim = "move_m@fat@a", title = "Style: Hommme", category="style"},
	["style_skinnyguy2"] = {anim = "ANIM_GROUP_MOVE_BALLISTIC", title = "Style: Hommme 2", category="style"},
	["style_skinnyguy3"] = {anim = "move_characters@franklin@fire", title = "Style: Hommme 3", category="style"},
	["style_skinnyguy4"] = {anim = "move_characters@michael@fire", title = "Style: Hommme 4", category="style"},
	["style_crooked"] = {anim = "move_ped_bucket", title = "Style: Courbé", category="style"},
	["style_grace"] = {anim = "move_m@money", title = "Style: Riche", category="style"},
	["style_gay"] = {anim = "MOVE_M@FEMME@", title = "Style: Gay", category="style"},
	["style_poseur"] = {anim = "move_m@posh@", title = "Style: Poseur", category="style"},
	["style_party"] = {anim = "anim@move_m@grooving@slow@", title = "Style: Danseur", category="style"},
	["style_cop"] = {anim = "move_m@intimidation@cop@unarmed", title = "Style: Flic", category="style"},
	["style_drunk"] = {anim = "move_m@drunk@moderatedrunk", title = "Style: Bourré", category="style"},
	["style_drunk2"] = {anim = "move_m@drunk@verydrunk", title = "Style: Bourré 2", category="style"},

	["standard"] = {category = 'face', anim = "mood_normal_1", title = "Face: Standard"},
	["stressedout"] = {category = 'face', anim = "mood_stressed_1", title = "Face: Stressé"},
	["obstinate"] = {category = 'face', anim = "effort_2", title = "Face: Obstiné"},
	["smiling"] = {category = 'face', anim = "mood_smug_1", title = "Face: Souriant"},
	["smiling2"] = {category = 'face', anim = "mood_happy_1", title = "Face: Souriant 2"},
	["smiling3"] = {category = 'face', anim = "mood_dancing_low_1", title = "Face: Souriant 3"},
	["angry"] = {category = 'face', anim = "mood_angry_1", title = "Face: Fâché"},
	["angry2"] = {category = 'face', anim = "pose_angry_1", title = "Face: Fâché 2"},
	["angry3"] = {category = 'face', anim = "effort_1", title = "Face: Fâché 3"},
	["shocked"] = {category = 'face', anim = "shocked_2", title = "Face: Choqué"},
	["shocked2"] = {category = 'face', anim = "pose_injured_1", title = "Face: Choqué 2"},
	["shocked3"] = {category = 'face', anim = "shocked_1", title = "Face: Choqué 3"},
	["shocked4"] = {category = 'face', anim = "smoking_hold_1", title = "Face: Choqué 4"},
	["grumpy"] = {category = 'face', anim = "mood_drivefast_1", title = "Face: Grincheux"},
	["whimsical"] = {category = 'face', anim = "mood_sulk_1", title = "Face: Capricieux"},
	["drunk6"] = {category = 'face', anim = "mood_drunk_1", title = "Face: Bourré"},
	["suspicious"] = {category = 'face', anim = "mood_aiming_1", title = "Face: Méfiant"},
	["weirdo"] = {category = 'face', anim = "effort_3", title = "Face: Bizarre"},
	["jaw"] = {category = 'face', anim = "electrocuted_1", title = "Face: Mâchoire"},
	["oneeye"] = {category = 'face', anim = "pose_aiming_1", title = "Face: Un oeil"},
	["sleeping"] = {category = 'face', anim = "dead_1", title = "Face: Dormir"},
	["sleeping2"] = {category = 'face', anim = "mood_sleeping_1", title = "Face: Dormir 2"},
	["give1"] = {category = 'shared', dict="mp_common", anim = "givetake1_a", title = "Donner 1", flags = 0},
	["give2"] = {category = 'shared', dict="mp_common", anim = "givetake1_b", title = "Donner 2", flags = 0},
	["guitar"] = { category = 'prop', title = "Guitare",  animDict = "switch@trevor@guitar_beatdown", animName = "001370_02_trvs_8_guitar_beatdown_idle_busker", animFlag = 51, bone = 28422, prop = "xx", propPos = {0.0, 2.0, 0.0, 0.0, 0.0, 0.0}},
	["guitar2"] = { category = 'prop', title = "Guitare 2",  animDict = "amb@world_human_musician@guitar@male@idle_a", animName = "idle_b", animFlag = 51, bone = 24818, prop = "prop_el_guitar_01", propPos = {-0.1, 0.31, 0.1, 0.0, 20.0, 150.0}},
	["guitar3"] = { category = 'prop', title = "Guitare 3",  animDict = "amb@world_human_musician@guitar@male@idle_a", animName = "idle_b", animFlag = 51, bone = 24818, prop = "prop_el_guitar_02", propPos = {-0.1, 0.31, 0.1, 0.0, 20.0, 150.0}},
	["guitar4"] = { category = 'prop', title = "Guitare 4",  animDict = "amb@world_human_musician@guitar@male@idle_a", animName = "idle_b", animFlag = 51, bone = 24818, prop = "prop_el_guitar_03", propPos = {-0.1, 0.31, 0.1, 0.0, 20.0, 150.0}},
	["guitar5"] = { category = 'prop', title = "Guitare 5",  animDict = "amb@world_human_musician@guitar@male@idle_a", animName = "idle_b", animFlag = 51, bone = 24818, prop = "prop_acc_guitar_01", propPos = {-0.1, 0.31, 0.1, 0.0, 20.0, 150.0}},
	["book"] = { category = 'prop', title = "Livre",  animDict = "cellphone@", animName = "cellphone_text_read_base", animFlag = 51, bone = 6286, prop = "prop_novel_01", propPos = {0.15, 0.03, -0.065, 0.0, 180.0, 90.0}},
	["notebook"] = { category = 'prop', title = "Cahier",  animDict = "missfam4", animName = "base", animFlag = 51, bone = 36029, prop = "p_amb_clipboard_01", propPos = {0.16, 0.08, 0.1, -130.0, -50.0, 0.0}},
  	["notebook3"] = { category = 'prop', title = "Cahier 3",  animDict = "missheistdockssetup1clipboard@base", animName = "base", animFlag = 51, bone = 18905, prop = "prop_notepad_01", propPos = {0.1, 0.02, 0.05, 10.0, 0.0, 0.0}},
  	["cleaning2"] = { category = 'prop', title = "Nettoyer",  animDict = "timetable@floyd@clean_kitchen@base", animName = "base", animFlag = 51, bone = 28422, prop = "prop_sponge_01", propPos = {0.0, 0.0, -0.01, 90.0, 0.0, 0.0}},
	["cleaning3"] = { category = 'prop', title = "Nettoyer 2",  animDict = "amb@world_human_maid_clean@", animName = "base", animFlag = 51, bone = 28422, prop = "prop_sponge_01", propPos = {0.0, 0.0, -0.01, 90.0, 0.0, 0.0}},
	["champagne"] = { category = 'prop', title = "Champagne",  animDict = "anim@mp_player_intupperspray_champagne", animName = "idle_a", animFlag = 51, bone = 28422, prop = "ba_prop_battle_champ_open", propPos = {0.0,0.0,0.0,0.0,0.0,0.0}},
	["newspaper"] = { category = 'prop', title = "Journal",  animDict = "amb@world_human_tourist_map@female@base", animName = "base", animFlag = 51, bone = 28422, prop = "prop_tourist_map_01", propPos = {-0.07, 0.0, 0.0, 90.0, 0.0, 0.0}},
	["begging"] = { category = 'prop', title = "Mendiant",  animDict = "amb@world_human_bum_freeway@male@base", animName = "base", animFlag = 51, bone = 58868, prop = "prop_beggers_sign_03", propPos = {0.19, 0.18, 0.0, 5.0, 0.0, 40.0}},
  	["megaphone"] = { category = 'prop', title = "Megaphone",  animDict = "weapons@first_person@aim_idle@generic@melee@knife@shared@core", animName = "wall_block", animFlag = 51, bone = 28422, prop = "prop_megaphone_01", propPos = {0.04, -0.01, 0.0, 90.0, 130.0, 220.0}},
  	["microphone"] = { category = 'prop', title = "Microphone",  animDict = "missmic4premiere", animName = "interview_short_lazlow", animFlag = 51, bone = 28422, prop = "p_ing_microphonel_01", propPos = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0}},
  	["microphone2"] = { category = 'prop', title = "Microphone 2",  animDict = "anim@random@shop_clothes@watches", animName = "base", animFlag = 49, bone = 60309, prop = "p_ing_microphonel_01", propPos = {0.10, 0.04, 0.010, -60.0, 60.0, 30.0}},
  	["sweeping2"] = { category = 'prop', title = "Balai 2",  animDict = "amb@world_human_janitor@male@idle_a", animName = "idle_a", animFlag = 49, bone = 28422 , prop = "prop_tool_broom", propPos = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0}},
  	["shovel"] = { category = 'prop', title = "Pelle",  animDict = "random@burial", animName = "a_burial", animFlag = 15, bone = 28422 , prop = "prop_ld_shovel", propPos = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0}},
  	["suitcase"] = { category = 'prop', title = "Valise",  animDict = "rcmepsilonism8", animName = "bag_handler_idle_a", animFlag = 50, bone = 57005 , prop = "prop_ld_case_01", propPos = {0.14, 0.0, -0.02, -90.0, 0.0, 90.0}},
  	["suitcase2"] = { category = 'prop', title = "Valise 2",  animDict = "rcmepsilonism8", animName = "bag_handler_idle_a", animFlag = 50, bone = 57005 , prop = "hei_p_attache_case_shut", propPos = {0.15, 0.0, 0.0, 0.0, 0.0, -90.0}},
  	["suitcase3"] = { category = 'prop', title = "Valise 3",  animDict = "rcmepsilonism8", animName = "bag_handler_idle_a", animFlag = 50, bone = 57005 , prop = "prop_ld_suitcase_01", propPos = {0.39, 0.0, 0.0, 0.0, 266.0, 60.0}},
  	["stick"] = { category = 'prop', title = "Coller 3",  event = "bluestark_animation:UseWalkingStick"},
	-- NEW
	["handshake"] = { category = 'synced', title = 'Poignée de main'},
	["handshake2"] = { category = 'synced', title = 'Poignée de main 2'},
	["hug"] = { category = 'synced', title = 'Étreinte'},
	["hug2"] = { category = 'synced', title = 'Étreinte 2'},
	["bro"] = { category = 'synced', title = 'Frère'},
	["bro2"] = { category = 'synced', title = 'Frère 2'},
	["give"] = { category = 'synced', title = 'Donner'},
	["give2"] = { category = 'synced', title = 'Donner 2'},
	["baseball"] = { category = 'synced', title = 'Baseball'},
	["stickup"] = { category = 'synced', title = 'Braquage'},
	["punch"] = { category = 'synced', title = 'Coup de poing'},
	["headbutt"] = { category = 'synced', title = 'Coup de tête'},
	["slap"] = { category = 'synced', title = 'Gifler'},
	["slap2"] = { category = 'synced', title = 'Gifler 2'},
	["giveblowjob"] = { category = 'synced', title = 'Blowjob NSFW'},
	["streetsex"] = { category = 'synced', title = 'Baise dans la rue NSFW'},

	["newscam"] = { category = 'prop', title = "News Camera",  animDict = "missfinale_c2mcs_1", animName = "fin_c2_mcs_1_camman", animFlag = 50, bone = 28422 , prop = "prop_v_cam_01", propPos = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0}},
	["rose"] = { category = 'prop', title = "Rose",  animDict = "anim@heists@humane_labs@finale@keycards", animName = "ped_a_enter_loop", animFlag = 50, bone = 18905 , prop = "prop_single_rose", propPos = {0.13, 0.15, 0.0, -100.0, 0.0, -20.0}},
	["smoke2"] = { category = 'prop', title = "Fumée 2",  animDict = "amb@world_human_aa_smoke@male@idle_a", animName = "idle_c", animFlag = 50, bone = 28422 , prop = "prop_cs_ciggy_01", propPos = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0}},
	["smoke3"] = { category = 'prop', title = "Fumée 3",  animDict = "amb@world_human_aa_smoke@male@idle_a", animName = "idle_b", animFlag = 50, bone = 28422 , prop = "prop_cs_ciggy_01", propPos = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0}},
	["smoke4"] = { category = 'prop', title = "Fumée 4",  animDict = "amb@world_human_smoking@female@idle_a", animName = "idle_b", animFlag = 50, bone = 28422 , prop = "prop_cs_ciggy_01", propPos = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0}},
	["bong"] = { category = 'prop', title = "Bang",  animDict = "anim@safehouse@bong", animName = "bong_stage3", animFlag = 50, bone = 18905 , prop = "hei_heist_sh_bong_01", propPos = {0.10,-0.25,0.0,95.0,190.0,180.0}},
	["mugshot"] = { category = 'prop', title = "Identité",  animDict = "mp_character_creation@customise@male_a", animName = "loop", animFlag = 50, bone = 58868 , prop = "prop_police_id_board", propPos = {0.12, 0.24, 0.0, 5.0, 0.0, 70.0}},

	["donut"] = { category = 'prop', title = "Donut",  animDict = "mp_player_inteat@burger", animName = "mp_player_int_eat_burger", animFlag = 50, bone = 18905 , prop = "prop_amb_donut", propPos = {0.13, 0.05, 0.02, -50.0, 16.0, 60.0}},
	["burger"] = { category = 'prop', title = "Burger",  animDict = "mp_player_inteat@burger", animName = "mp_player_int_eat_burger", animFlag = 50, bone = 18905 , prop = "prop_cs_burger_01", propPos = {0.13, 0.05, 0.02, -50.0, 16.0, 60.0}},
	["sandwich"] = { category = 'prop', title = "Sandwich",  animDict = "mp_player_inteat@burger", animName = "mp_player_int_eat_burger", animFlag = 50, bone = 18905 , prop = "prop_sandwich_01", propPos = {0.13, 0.05, 0.02, -50.0, 16.0, 60.0}},
	["teddy"] = { category = 'prop', title = "Nounours",  animDict = "impexp_int-0", animName = "mp_m_waremech_01_dual-0", animFlag = 50, bone = 24817 , prop = "v_ilev_mr_rasberryclean", propPos = {-0.20, 0.46, -0.016, -180.0, -90.0, 0.0}},
	["bouquet"] = { category = 'prop', title = "Bouquet",  animDict = "impexp_int-0", animName = "mp_m_waremech_01_dual-0", animFlag = 50, bone = 24817 , prop = "prop_snow_flower_02", propPos = {-0.29, 0.40, -0.02, -90.0, -90.0, 0.0}},
	["backpack"] = { category = 'prop', title = "Sac à dos",  animDict = "move_p_m_zero_rucksack", animName = "idle", animFlag = 50, bone = 24818 , prop = "p_michael_backpack_s", propPos = {0.07, -0.11, -0.05, 0.0, 90.0, 175.0}},
	["beast"] = {title = "Bête", category = "other", animDict = "anim@mp_fm_event@intro", animName = "beast_transform", animFlag = 15},
	["jazzhands"] = {title = "Jazzhands", category = "other", animDict = "anim@mp_player_intcelebrationfemale@jazz_hands", animName = "jazz_hands", animFlag = 15},
	["spiderman"] = {title = "Spider-Man", category = "other", animDict = "missexile3", animName = "ex03_train_roof_idle", animFlag = 15},
	["rabbit"] = {title = "Lapin", category = "other", animDict = "random@peyote@rabbit", animName = "wakeup", animFlag = 15},
	["dog"] = {title = "Chien", category = "other", animDict = "random@peyote@dog", animName = "wakeup", animFlag = 15},

	["style_gangster3"] = {anim = "move_m@gangster@var_e", title = "Style: Gangster 3", category="style"},
	["style_gangster4"] = {anim = "move_m@gangster@var_i", title = "Style: Gangster 4", category="style"},
	["style_grooving"] = {anim = "anim@move_m@grooving@", title = "Style: Grooving", category="style"},
	["style_guard"] = {anim = "move_m@prison_gaurd", title = "Style: Garde", category="style"},
	["style_handcuffs"] = {anim = "move_m@prisoner_cuffed", title = "Style: Menotté", category="style"},
	["style_heels"] = {anim = "move_f@heels@c", title = "Style: Talons", category="style"},
	["style_heels2"] = {anim = "move_f@heels@d", title = "Style: Talons 2", category="style"},
	["style_trash"] = {anim = "clipset@move@trash_fast_turn", title = "Style: SDF ", category="style"},
	["style_trash2"] = {anim = "missfbi4prepp1_garbageman", title = "Style: SDF 2", category="style"},
	["style_runner"] = {anim = "female_fast_runner", title = "Style: Sportif", category="style"},
	["style_chichi"] = {anim = "move_f@chichi", title = "Style: Chichi", category="style"},
	["style_confident"] = {anim = "move_m@confident", title = "Style: Sur de soi", category="style"},
	["style_cop2"] = {anim = "move_m@business@b", title = "Style: Flic 2", category="style"},
	["style_flee"] = {anim = "move_f@flee@a", title = "Style: Fuir", category="style"},

	
}
Config.SyncedAnimations = {
	["handshake2"] = {"mp_ped_interaction", "handshake_guy_a", "Poignée de main 2", "handshake2", AnimationOptions =
	{
		EmoteMoving = true,
		EmoteDuration = 3000,
		SyncOffsetFront = 0.9
	}},
	["handshake"] = {"mp_ped_interaction", "handshake_guy_b", "Poignée de main", "handshake", AnimationOptions =
	{
		EmoteMoving = true,
		EmoteDuration = 3000
	}},
	["hug2"] = {"mp_ped_interaction", "kisses_guy_a", "Étreinte 2", "hug2", AnimationOptions =
	{
		EmoteMoving = false,
		EmoteDuration = 5000,
		SyncOffsetFront = 1.05,
	}},
	["hug"] = {"mp_ped_interaction", "kisses_guy_b", "Étreinte", "hug", AnimationOptions =
	{
		EmoteMoving = false,
		EmoteDuration = 5000,
		SyncOffsetFront = 1.13
	}},
	["bro2"] = {"mp_ped_interaction", "hugs_guy_a", "Frère", "bro2", AnimationOptions =
	{
		 SyncOffsetFront = 1.14
	}},
	["bro"] = {"mp_ped_interaction", "hugs_guy_b", "Frère 2", "bro", AnimationOptions =
	{
		 SyncOffsetFront = 1.14
	}},
	["give2"] = {"mp_common", "givetake1_a", "Donner", "give2", AnimationOptions =
	{
		EmoteMoving = true,
		EmoteDuration = 2000
	}},
	["give"] = {"mp_common", "givetake1_b", "Donner 2", "give", AnimationOptions =
	{
		EmoteMoving = true,
		EmoteDuration = 2000
	}},
	["baseball"] = {"anim@arena@celeb@flat@paired@no_props@", "baseball_a_player_a", "Baseball", "baseballthrow"},
	["baseballthrow"] = {"anim@arena@celeb@flat@paired@no_props@", "baseball_a_player_b", "Lancer Balle", "baseball"},
	["stickup"] = {"random@countryside_gang_fight", "biker_02_stickup_loop", "Braquage 2", "stickupscared", AnimationOptions =
	{
		EmoteLoop = true,
		EmoteMoving = true,
	}},
	["stickupscared"] = {"missminuteman_1ig_2", "handsup_base", "Braquage", "stickup", AnimationOptions =
	{
	   EmoteMoving = true,
	   EmoteLoop = true,
	}},
	["punch"] = {"melee@unarmed@streamed_variations", "plyr_takedown_rear_lefthook", "Coup de poing", "punched"},
	["punched"] = {"melee@unarmed@streamed_variations", "victim_takedown_front_cross_r", "Recevoir coup de poing", "punch"},
	["headbutt"] = {"melee@unarmed@streamed_variations", "plyr_takedown_front_headbutt", "Coup de tête", "headbutted"},
	["headbutted"] = {"melee@unarmed@streamed_variations", "victim_takedown_front_headbutt", "Recevoir coup de tête", "headbutt"},
	["slap2"] = {"melee@unarmed@streamed_variations", "plyr_takedown_front_backslap", "Gifler 2", "slapped2", AnimationOptions =
	{
		EmoteLoop = true,
		EmoteMoving = true,
		EmoteDuration = 2000,
	}},
	["slap"] = {"melee@unarmed@streamed_variations", "plyr_takedown_front_slap", "Gifler", "slapped", AnimationOptions =
	{
		EmoteLoop = true,
		EmoteMoving = true,
		EmoteDuration = 2000,
	}},
	["slapped"] = {"melee@unarmed@streamed_variations", "victim_takedown_front_slap", "Gifle", "slap"},
	["slapped2"] = {"melee@unarmed@streamed_variations", "victim_takedown_front_backslap", "Gifle 2", "slap2"},
	["ReceiveBlowjob"] = {"misscarsteal2pimpsex", "pimpsex_punter", "Recevoir une pipe", "giveblowjob", AnimationOptions =
		{
		EmoteMoving = false,
		EmoteDuration = 30000,
		SyncOffsetFront = 0.63
	}},
	["giveblowjob"] = {"misscarsteal2pimpsex", "pimpsex_hooker", "Blowjob NSFW", "ReceiveBlowjob", AnimationOptions =
	{
		EmoteMoving = false,
		EmoteDuration = 30000,
		SyncOffsetFront = 0.63
	}},
	["streetsex"] = {"misscarsteal2pimpsex", "shagloop_pimp", "Baise dans la rue", "StreetSexFemale", AnimationOptions =
	{
		EmoteMoving = false,
		EmoteLoop = true,
		SyncOffsetFront = 0.50
	}},
	["StreetSexFemale"] = {"misscarsteal2pimpsex", "shagloop_hooker", "Baise dans la rue", "streetsex", AnimationOptions =
	{
		EmoteMoving = false,
		EmoteLoop = true,
		SyncOffsetFront = -0.50
	}},
}