GM.Weapon = GM.Weapon or {}

GM.Weapon["list_chest"] = {
    [`WEAPON_UNARMED`] = {parameters = {anim = false, scoped = false, shakeCam = 0, infiniteAmmo = false}},

    [`WEAPON_KNIFE`] = {parameters = {anim = true, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_NIGHTSTICK`] = {parameters = {anim = false, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_HAMMER`] = {parameters = {anim = true, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_BAT`] = {parameters = {anim = true, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_CROWBAR`] = {parameters = {anim = true, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_GOLFCLUB`] = {parameters = {anim = true, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_BOTTLE`] = {parameters = {anim = true, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_DAGGER`] = {parameters = {anim = true, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_HATCHET`] = {parameters = {anim = true, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_KNUCKLE`] = {parameters = {anim = false, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_MACHETE`] = {parameters = {anim = true, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_MACHETE`] = {parameters = {anim = true, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_FLASHLIGHT`] = {parameters = {anim = false, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_SWITCHBLADE`] = {parameters = {anim = false, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_BATTLEAXE`] = {parameters = {anim = true, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_POOLCUE`] = {parameters = {anim = true, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_WRENCH`] = {parameters = {anim = true, scoped = false, shakeCam = 0, infiniteAmmo = false}},

    [`WEAPON_PISTOL`] = {parameters = {anim = true, scoped = false, shakeCam = 0.025, infiniteAmmo = false}},
    [`WEAPON_PISTOL_MK2`] = {parameters = {anim = true, scoped = false, shakeCam = 0.03, infiniteAmmo = false}},
    [`WEAPON_COMBATPISTOL`] = {parameters = {anim = false, scoped = false, shakeCam = 0.03, infiniteAmmo = false}},
    [`WEAPON_PISTOL50`] = {parameters = {anim = true, scoped = false, shakeCam = 0.05, infiniteAmmo = false}},
    [`WEAPON_SNSPISTOL`] = {parameters = {anim = true, scoped = false, shakeCam = 0.02, infiniteAmmo = false}},
    [`WEAPON_SNSPISTOL_MK2`] = {parameters = {anim = true, scoped = false, shakeCam = 0.025, infiniteAmmo = false}},
    [`WEAPON_HEAVYPISTOL`] = {parameters = {anim = true, scoped = false, shakeCam = 0.03, infiniteAmmo = false}},
    [`WEAPON_VINTAGEPISTOL`] = {parameters = {anim = true, scoped = false, shakeCam = 0.025, infiniteAmmo = false}},
    [`WEAPON_MARKSMANPISTOL`] = {parameters = {anim = true, scoped = false, shakeCam = 0.03, infiniteAmmo = false}},
    [`WEAPON_REVOLVER`] = {parameters = {anim = true, scoped = false, shakeCam = 0.045, infiniteAmmo = false}},
    [`WEAPON_REVOLVER_MK2`] = {parameters = {anim = true, scoped = false, shakeCam = 0.055, infiniteAmmo = false}},
    [`WEAPON_DOUBLEACTION`] = {parameters = {anim = true, scoped = false, shakeCam = 0.025, infiniteAmmo = false}},
    [`WEAPON_APPISTOL`] = {parameters = {anim = true, scoped = false, shakeCam = 0.05, infiniteAmmo = false}},
    [`WEAPON_STUNGUN`] = {parameters = {anim = false, scoped = false, shakeCam = 0.01, infiniteAmmo = false}},
    [`WEAPON_FLAREGUN`] = {parameters = {anim = true, scoped = false, shakeCam = 0.01, infiniteAmmo = false}},

    [`WEAPON_MICROSMG`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.035, infiniteAmmo = false}},
    [`WEAPON_MACHINEPISTOL`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.035, infiniteAmmo = false}},
    [`WEAPON_MINISMG`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.035, infiniteAmmo = false}},
    [`WEAPON_SMG`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.045, infiniteAmmo = false}},
    [`WEAPON_SMG_MK2`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.055, infiniteAmmo = false}},
    [`WEAPON_ASSAULTSMG`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.05, infiniteAmmo = false}},
    [`WEAPON_COMBATPDW`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.045, infiniteAmmo = false}},
    [`WEAPON_MG`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.07, infiniteAmmo = false}},
    [`WEAPON_COMBATMG`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.08, infiniteAmmo = false}},
    [`WEAPON_COMBATMG_MK2`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.085, infiniteAmmo = false}},
    [`WEAPON_GUSENBERG`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.05, infiniteAmmo = false}},

    [`WEAPON_ASSAULTRIFLE`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.07, infiniteAmmo = false}},
    [`WEAPON_ASSAULTRIFLE_MK2`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.075, infiniteAmmo = false}},
    [`WEAPON_CARBINERIFLE`] = {parameters = {anim = true, onlyBag = false, scoped = false, shakeCam = 0.06, infiniteAmmo = false}},
    [`WEAPON_CARBINERIFLE_MK2`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.065, infiniteAmmo = false}},
    [`WEAPON_ADVANCEDRIFLE`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.06, infiniteAmmo = false}},
    [`WEAPON_SPECIALCARBINE`] = {parameters = {anim = true, onlyBag = false, scoped = false, shakeCam = 0.06, infiniteAmmo = false}},
    [`WEAPON_SPECIALCARBINE_MK2`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.075, infiniteAmmo = false}},
    [`WEAPON_BULLPUPRIFLE`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.05, infiniteAmmo = false}},
    [`WEAPON_BULLPUPRIFLE_MK2`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.065, infiniteAmmo = false}},
    [`WEAPON_COMPACTRIFLE`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.05, infiniteAmmo = false}},
    [`WEAPON_SCAR17FM`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.05, infiniteAmmo = false}},

    [`WEAPON_PUMPSHOTGUN`] = {parameters = {anim = true, onlyBag = false, scoped = false, shakeCam = 0.07, infiniteAmmo = false}},
    [`WEAPON_PUMPSHOTGUN_MK2`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.085, infiniteAmmo = false}},
    [`WEAPON_SAWNOFFSHOTGUN`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.06, infiniteAmmo = false}},
    [`WEAPON_BULLPUPSHOTGUN`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.08, infiniteAmmo = false}},
    [`WEAPON_ASSAULTSHOTGUN`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.12, infiniteAmmo = false}},
    [`WEAPON_MUSKET`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.04, infiniteAmmo = false}},
    [`WEAPON_HEAVYSHOTGUN`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.13, infiniteAmmo = false}},
    [`WEAPON_DBSHOTGUN`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.05, infiniteAmmo = false}},
    [`WEAPON_AUTOSHOTGUN`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.08, infiniteAmmo = false}},

    [`WEAPON_SNIPERRIFLE`] = {parameters = {anim = true, onlyBag = true, scoped = true, shakeCam = 0.2, infiniteAmmo = false}},
    [`WEAPON_HEAVYSNIPER`] = {parameters = {anim = true, onlyBag = true, scoped = true, shakeCam = 0.3, infiniteAmmo = false}},
    [`WEAPON_HEAVYSNIPER_MK2`] = {parameters = {anim = true, onlyBag = true, scoped = true, shakeCam = 0.35, infiniteAmmo = false}},
    [`WEAPON_MARKSMANRIFLE`] = {parameters = {anim = true, onlyBag = true, scoped = true, shakeCam = 0.1, infiniteAmmo = false}},
    [`WEAPON_MARKSMANRIFLE_MK2`] = {parameters = {anim = true, onlyBag = true, scoped = true, shakeCam = 0.1, infiniteAmmo = false}},

    [`WEAPON_GRENADELAUNCHER`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.08, infiniteAmmo = false}},
    [`WEAPON_RPG`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.9, infiniteAmmo = false}},
    [`WEAPON_STINGER`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_MINIGUN`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.2, infiniteAmmo = false}},
    [`WEAPON_FIREWORK`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.5, infiniteAmmo = false}},
    [`WEAPON_RAILGUN`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 1.0, infiniteAmmo = false}},
    [`WEAPON_HOMINGLAUNCHER`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.9, infiniteAmmo = false}},
    [`WEAPON_COMPACTLAUNCHER`] = {parameters = {anim = true, onlyBag = true, scoped = false, shakeCam = 0.08, infiniteAmmo = false}},

    [`WEAPON_GRENADE`] = {parameters = {anim = false, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_STICKYBOMB`] = {parameters = {anim = false, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_PROXMINE`] = {parameters = {anim = false, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_SMOKEGRENADE`] = {parameters = {anim = false, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_BZGAS`] = {parameters = {anim = false, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_MOLOTOV`] = {parameters = {anim = false, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_FIREEXTINGUISHER`] = {parameters = {anim = true, scoped = false, shakeCam = 0, infiniteAmmo = true}},
    [`WEAPON_PETROLCAN`] = {parameters = {anim = true, scoped = false, shakeCam = 0, infiniteAmmo = true}},
    [`WEAPON_BALL`] = {parameters = {anim = false, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_SNOWBALL`] = {parameters = {anim = false, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_FLARE`] = {parameters = {anim = false, scoped = false, shakeCam = 0, infiniteAmmo = false}},
    [`WEAPON_PIPEBOMB`] = {parameters = {anim = false, scoped = false, shakeCam = 0, infiniteAmmo = false}}
}

GM.Weapon["list_bags"] = {
    [1] = true,
	[2] = true,
	[3] = true,
	[4] = true,
	[5] = true,
	[6] = true,
	[7] = true,
	[8] = true,
	[9] = true,
	[10] = true,
	[11] = true,
	[12] = true,
	[13] = true,
	[14] = true,
	[15] = true,
	[16] = true,
	[17] = true,
	[18] = true,
	[19] = true,
	[20] = true,
	[21] = true,
	[22] = true,
	[23] = true,
	[24] = true,
	[25] = true,
	[26] = true,
	[27] = true,
	[28] = true,
	[29] = true,
	[30] = true,
	[31] = true,
	[32] = true,
	[33] = true,
	[34] = true,
	[35] = true,
	[36] = true,
	[37] = true,
	[38] = true,
	[39] = true,
	[40] = true,
	[41] = true,
	[42] = true,
	[43] = true,
	[44] = true,
	[45] = true,
	[46] = true,
	[47] = true,
	[48] = true,
	[49] = true,
	[50] = true,
	[51] = true,
	[52] = true,
	[53] = true,
	[54] = true,
	[55] = true,
	[56] = true,
	[57] = true,
	[58] = true,
	[59] = true,
	[60] = true,
	[61] = true,
	[62] = true,
	[63] = true,
	[64] = true,
	[65] = true,
	[66] = true,
	[67] = true,
	[68] = true,
	[69] = true,
	[70] = true,
	[71] = true,
	[72] = true,
	[73] = true,
	[74] = true,
	[75] = true,
	[76] = true,
	[77] = true,
	[78] = true,
	[79] = true,
	[80] = true,
	[81] = true,
	[82] = true,
	[83] = true,
	[84] = true,
	[85] = true,
	[86] = true,
	[87] = true,
	[88] = true,
	[89] = true,
	[90] = true,
	[91] = true,
	[92] = true,
	[93] = true,
	[94] = true,
	[95] = true,
	[96] = true,
}