exports("GetWeight", function()
    return ScriptClient.Player.Inventory:GetWeight()
end)
exports("GetItemBy", function(findBy)
    return ScriptClient.Player.Inventory:GetItemBy(findBy)
end)
exports("GetInventoryItems", function()
    return ScriptClient.Player.Inventory.Items
end)
exports("GetItemQuantityBy", function(findBy)
    return ScriptClient.Player.Inventory:GetItemQuantityBy(findBy)
end)
exports("OpenStash", function(uniqueID)
    TriggerServerEvent("Inventory:OPEN_STASH", uniqueID)
end)
exports("GetRegisteredItems", function()
    return ScriptShared.Items.Registered
end)
exports("GetRegisteredItem", function(itemName)
    return ScriptShared.Items:Get(itemName)
end)
